# -*- coding: utf-8 -*-
"""[NCKH] Gold trade.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cJsxXikQyC6qORfOT01Y3BZ5B_jBvHJu
"""

#Chương 1. Import Libraries
import warnings
warnings.filterwarnings("ignore")

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import TimeSeriesSplit
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix
)

from sklearn.preprocessing import StandardScaler

from xgboost import XGBClassifier

import shap

#Chương 2. Load Data
df = pd.read_csv("/content/gold_price_2015_2025_cleaned (1).csv")

print(df.shape)

df.head()

import numpy as np
#Chương 3. Exploratory Data Analysis

#Kiểm tra

df.info()
df.describe()

#Kiểm tra NA

df.isnull().sum()

#Kiểm tra phân bố dữ liệu

sns.histplot(df["Close"])

#Heatmap

sns.heatmap(df.select_dtypes(include=np.number).corr(), cmap="coolwarm")

#Chương 4. Feature Engineering (là EMA, MA,...)

#Chương 5. Tạo Label
# future_return
# =
# Close(t+5)
# /Close(t)-1

# Nếu

# future_return>1%

# ↓

# BUY

# Nếu

# future_return<-1%

# ↓

# SELL

# Ngược lại

# ↓

# HOLD

# Ta thu được

# 0 = SELL

# 1 = HOLD

# 2 = BUY

# ==========================================================
# CHAPTER 5: LABEL GENERATION
# ==========================================================

holding_period = 5

future_return = (
    df["Close"].shift(-holding_period) - df["Close"]
) / df["Close"]

df["Future_Return"] = future_return
buy_threshold = 0.01
sell_threshold = -0.01

conditions = [

    df["Future_Return"] > buy_threshold,

    df["Future_Return"] < sell_threshold

]

choices = [

    2,      # BUY

    0       # SELL

]

df["Label"] = np.select(
    conditions,
    choices,
    default=1       # HOLD
)

print(df["Label"].value_counts())

mapping = {

    0:"SELL",

    1:"HOLD",

    2:"BUY"

}

print(

df["Label"]

.map(mapping)

.value_counts()

)

df = df.dropna().reset_index(drop=True)

